# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Descent
version:      v0.0.1
version_from: lib/XML/Descent.pm
installdirs:  site
requires:
    Class::Std:                    0
    Test::More:                    0
    version:                       0
    XML::TokeParser:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
